# Generated by Django 4.2.2 on 2023-06-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='domain_list',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
