# Generated by Django 4.2.2 on 2023-06-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_collection_domain_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='domain_list',
            field=models.TextField(blank=True, help_text='To edit this collection, save the list of domains here.', null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='domains',
            field=models.ManyToManyField(editable=False, to='core.domain'),
        ),
    ]
