# Generated by Django 3.2.19 on 2023-06-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_collection_domain_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='hash',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='domain',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
