# Generated by Django 3.2.19 on 2023-06-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230609_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_sync_block', models.CharField(default='14909991', max_length=200)),
            ],
            options={
                'verbose_name': 'Sync Status',
            },
        ),
    ]
