# Generated by Django 3.2.19 on 2023-06-09 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_syncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
