# Generated by Django 3.2.19 on 2023-06-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_domain_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syncstatus',
            name='domain_sync_block',
        ),
        migrations.AddField(
            model_name='syncstatus',
            name='opensea_last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
