# Generated by Django 3.2.19 on 2023-06-09 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
