# Generated by Django 3.2.19 on 2023-06-09 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_delete_listing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.IntegerField(choices=[('OPENSEA', 1)])),
                ('token_id', models.CharField(blank=True, max_length=500, null=True)),
                ('seller', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='AVAX', max_length=50)),
                ('decimals', models.IntegerField(default=0)),
            ],
        ),
    ]
