# Generated by Django 3.2.19 on 2023-06-09 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_listing_last_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='token_id',
        ),
        migrations.AddField(
            model_name='listing',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.domain'),
        ),
    ]
