# Generated by Django 3.2.19 on 2023-06-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230609_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domain',
            name='hash',
        ),
    ]
